# Generated by Django 3.0 on 2019-12-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('codigoarea', models.CharField(db_column='codigoArea', max_length=4, primary_key=True, serialize=False)),
                ('nombrearea', models.CharField(db_column='nombreArea', max_length=62)),
                ('abreviatura', models.CharField(db_column='Abreviatura', max_length=19)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('id_area', models.CharField(max_length=3)),
                ('nombre_empleado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('codigoactivo', models.CharField(db_column='CodigoActivo', max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=30)),
                ('version', models.CharField(db_column='version', max_length=8)),
                ('licencia', models.CharField(db_column='licencia', max_length=2)),
                ('tipoequipo', models.CharField(db_column='TipoEquipo', max_length=6)),
            ],
            options={
                'db_table': 'software',
                'managed': False,
            },
        ),
    ]
