# Generated by Django 3.0.1 on 2020-02-07 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='estabilizador',
            options={},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pc',
            options={},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={},
        ),
    ]
