# Generated by Django 3.0.1 on 2020-02-07 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20200207_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='estabilizador',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pc',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'managed': False},
        ),
    ]
