# Generated by Django 3.0.1 on 2020-01-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_area_empleado_software'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=25)),
                ('marca_equipo', models.CharField(blank=True, max_length=25, null=True)),
                ('modelo_equipo', models.CharField(blank=True, max_length=25, null=True)),
                ('estado_equipo', models.CharField(max_length=15)),
                ('numero_serie', models.CharField(blank=True, max_length=15, null=True)),
                ('codigo_activo', models.CharField(blank=True, max_length=12, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'equipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estabilizador',
            fields=[
                ('id_estabilizador', models.AutoField(primary_key=True, serialize=False)),
                ('marca_estabilizador', models.CharField(max_length=16)),
                ('potencia_watts', models.CharField(blank=True, max_length=10, null=True)),
                ('potencia_va', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_estabilizador', models.CharField(max_length=13)),
                ('numero_serie', models.CharField(blank=True, max_length=15, null=True)),
                ('codigo_activo', models.CharField(blank=True, max_length=12, null=True)),
                ('estado_estabilizador', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'estabilizador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('id_pc', models.AutoField(primary_key=True, serialize=False)),
                ('procesador_pc', models.CharField(max_length=20)),
                ('velocidad_pc', models.CharField(max_length=10)),
                ('memoria_ram', models.CharField(max_length=7)),
                ('almacenamiento', models.CharField(max_length=7)),
                ('tarjeta_video', models.CharField(blank=True, max_length=15, null=True)),
                ('marca', models.CharField(blank=True, max_length=8, null=True)),
                ('tipo_equipo', models.CharField(max_length=8)),
                ('numero_serie', models.CharField(blank=True, max_length=15, null=True)),
                ('modelo', models.CharField(blank=True, max_length=15, null=True)),
                ('codigo_activo', models.CharField(blank=True, max_length=12, null=True)),
                ('sistema_operativo', models.CharField(max_length=11)),
                ('estado', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'pc',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Hardware',
        ),
    ]
