# Generated by Django 3.0.1 on 2020-02-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20200116_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'marca',
                'managed': False,
            },
        ),
    ]
