# Generated by Django 3.0.6 on 2020-11-28 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20200207_0024'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='equipo',
            table='harware_perifericos_otros',
        ),
        migrations.AlterModelTable(
            name='estabilizador',
            table='hardware_regulador_voltaje',
        ),
        migrations.AlterModelTable(
            name='pc',
            table='hardware_computadora',
        ),
    ]
